name: validate

on:
  workflow_call:
    inputs:
      environment_url:
        description: "the environment to validate"
        required: true
        default: "https://staging.rpc.walletconnect.com"
        type: string

  workflow_dispatch:
    inputs:
      environment_url:
        description: "the environment to validate"
        required: true
        default: "https://staging.rpc.walletconnect.com"
        type: string 

jobs:
  validate:
    # Compiles Rust logic so let's use the runners
    runs-on:
      group: ubuntu-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run integration tests
        run: cargo test --test integration
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          RPC_URL: ${{inputs.environment_url}}
